version: "3.9"

services:
  app:
    user: root
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=147.45.40.23
      - DB_NAME=hrhubdb
      - DB_USER=denis
      - DB_PASS=admin1337
      - DB_PORT=5432