# Generated by Django 5.0.6 on 2024-07-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceaccount',
            name='app_password',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceaccount',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
