# Generated by Django 5.0.6 on 2024-07-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0003_alter_serviceaccount_app_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceaccount',
            name='access_token',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceaccount',
            name='refresh_token',
            field=models.CharField(blank=True, null=True),
        ),
    ]
