# Generated by Django 5.0.6 on 2024-07-06 23:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0004_serviceaccount_access_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceaccount',
            name='service_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='serviceaccount',
            unique_together={('user_id', 'service_user_id')},
        ),
    ]
