# Generated by Django 5.0.6 on 2024-07-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0005_serviceaccount_service_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceaccount',
            name='service_user_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
