# Generated by Django 5.0.6 on 2024-06-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='from_user_id',
        ),
        migrations.AddField(
            model_name='message',
            name='from_username',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='from_userphone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
