# Generated by Django 5.0.6 on 2024-06-29 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging_app', '0002_remove_message_chat_id_remove_message_from_user_id_and_more'),
        ('services_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services_app.serviceaccount'),
        ),
        migrations.DeleteModel(
            name='ServiceAccount',
        ),
    ]
