# Generated by Django 5.0.6 on 2024-06-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging_app', '0003_alter_message_account_delete_serviceaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='personal_chat_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
