# Generated by Django 5.0.6 on 2024-07-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging_app', '0004_message_is_read_message_personal_chat_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='received_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
