# Generated by Django 5.0.6 on 2024-06-30 20:08

from django.db import migrations, models


def update_emails(apps, schema_editor):
    User = apps.get_model('user_app', 'User')
    for i, user in enumerate(User.objects.all()):
        user.email = f'user{i}@example.com'
        user.save()


class Migration(migrations.Migration):
    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, null=True),
        ),
        migrations.RunPython(update_emails),
    ]
