# Generated by Django 5.0.6 on 2024-07-13 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_customuser_membersofgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membersofgroup',
            name='user',
        ),
    ]
