# Generated by Django 5.0.6 on 2024-07-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_customuser_profession_membersofgroup_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersofgroup',
            name='service_name',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
