---
name: Checks

on: [push]

jobs:
    test-lint:
        name: Test and Lint
        runs-on: ubuntu-20.04
        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USER }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Checkout
              uses: actions/checkout@v4
            - name: Test
              run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
            - name: Lint
              run: docker-compose run --rm app sh -c "flake8"

    deploy:
        name: Deploy
        needs: test-lint
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup SSH
              uses: webfactory/ssh-agent@v0.8.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            - name: Add known hosts
              run: |
                  mkdir -p ~/.ssh
                  ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
            - name: Deploy to Server
              run: |
                  ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "\
                  echo 'Starting deployment...' && \
                  mkdir -p ~/hrhub-backend && \
                  cd ~/hrhub-backend && \
                  git pull && \
                  docker-compose pull && \
                  docker-compose down --remove-orphans && \
                  docker-compose up -d --build && \
                  echo 'Deployment completed successfully'"
              timeout-minutes: 10
