name: Deploy to Ubuntu Server

on:
    push:
        branches:
            - dev-d # или ваша основная ветка

jobs:
    deploy:
        name: Deploy to Server
        runs-on: ubuntu-20.04
        steps:
            - name: Install sshpass
              run: sudo apt-get install sshpass
            - name: Deploy to Server
              env:
                  HOST: '147.45.40.23'
                  USER: 'hr-hub'
                  PASSWORD: 'admin1337'
              run: |
                  sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no $USER@$HOST << EOF
                    docker pull ${{ secrets.DOCKERHUB_USER }}/hrhub:latest
                    docker-compose down
                    docker-compose up -d
                  EOF
