name: Deploy to Ubuntu Server (dev-d)

on:
    push:
        branches:
            - dev-d # или ваша основная ветка

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install sshpass
              run: sudo apt-get install sshpass

            - name: Deploy to Server
              env:
                  HOST: '147.45.40.23'
                  USER: 'hr-hub'
                  PASSWORD: 'admin1337'
              run: |
                  sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no $USER@$HOST << EOF
                    cd .
                    git pull origin main
                    docker-compose down
                    docker-compose up --build -d
                  EOF
